### ISSUE TITLE
Tiny patch for issues, can not delete one or many data

### ISSUE THREAD

**Issue by salmanagustian** [ChristopheCVB/strapi-plugin-soft-delete#10] opened 2024-01-22 05:55 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `strapi-plugin-soft-delete@0.9.4` for the project I'm working on.

Here is the diff that solved my problem:

```
diff --git a/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js b/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
index 5e664e9..c368c74 100644
--- a/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
+++ b/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
@@ -15,6 +15,7 @@ const getService = (name) => {
 };
 exports.getService = getService;
 const eventHubEmit = async (params) => {
+    if (!params.uid) { return };
     const modelDef = strapi.getModel(params.uid);
     const sanitizedEntity = await utils_1.sanitize.sanitizers.defaultSanitizeOutput(modelDef, params.entity);
     strapi.eventHub.emit(params.event, {


diff --git a/node_modules/strapi-plugin-soft-delete/server/utils/index.ts b/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
index 6c541d9..d3d4efa 100644
--- a/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
+++ b/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
@@ -29,6 +29,7 @@ declare type CustomEventHubEmit = {
 });
 
 export const eventHubEmit = async (params: CustomEventHubEmit) => {
+  if (!params.uid) { return };
   const modelDef = strapi.getModel(params.uid);
   const sanitizedEntity = await sanitize.sanitizers.defaultSanitizeOutput(
     modelDef,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ChristopheCVB** [comment] 2024-02-26 11:27
Closing as duplicate of #9

**Closed as completed by ChristopheCVB** 2024-02-26 11:27 UTC
