### ISSUE TITLE
Website crash when Bulk delete records from Content Manager in Strapi Admin

### ISSUE THREAD

**Issue by mukesh-thakur-dy** [ChristopheCVB/strapi-plugin-soft-delete#11] opened 2024-02-15 10:36 UTC
### Required System information

- Node.js version: 20.11.1
- NPM version: 10.2.4
- Strapi version: 4.20.1
- Database: MySql
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript 

### Describe the bug
When i select any item from listing, and click on delete button. the Strapi Admin site is crash with below error.
![image](https://github.com/ChristopheCVB/strapi-plugin-soft-delete/assets/148182953/9a510a22-b255-4b84-a13e-be104933bb0f)

if remove this plugin from Strapi, the bulk delete is working without any error.

### Steps to reproduce the behavior

1. Go to Content Manager
2. Click on check box for Select item 
3. Click on Delete button which is display after filter button
4. Strapi admin crash after that action with above error.

![image](https://github.com/ChristopheCVB/strapi-plugin-soft-delete/assets/148182953/9e5dda40-5c2a-4f12-b59d-5c818e7bcfef)

### Expected behavior

Delete the item without error.

**Comment by AnkitGujaria1018** [comment] 2024-02-15 10:55
@ChristopheCVB  I am getting same error while bulk deleting any items

**Comment by ChristopheCVB** [comment] 2024-02-26 11:27
Closing as duplicate of #9

**Closed as completed by ChristopheCVB** 2024-02-26 11:27 UTC
Labels: bug
